### ISSUE TITLE
Set up 'uptime robot' or similar

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/docs#113]
We should set up [Uptime Robot](https://uptimerobot.com) to notify dama@bnl.gov when any of our public sites fall over. Prompted by https://github.com/scikit-beam/scikit-beam/issues/543

**Comment by danielballan** [comment]
Sites we want to monitor, off the top of my head:

https://nsls-ii.github.io
https://nsls-ii.github.io/scientific-python-cookiecutter/
https://caproto.github.io/caproto/
https://blueskyproject.io and all of the sub-sites like https://blueskyproject.io/bluesky listed in the "Documentation" navigation menu
https://scikit-beam.github.io/scikit-beam/

**Comment by jklynch** [comment]
Done. I am the Uptime Robot account holder, which is not great.

**Comment by danielballan** [comment]
Is it possible to make a new account associated with dama@bnl.gov and put the password in a file like `/keybase/team/dama/uptime_robot_password`?

**Comment by jklynch** [comment]
The email address has to be verified so dama@bnl.gov may not work. I'll try it.

**Comment by jklynch** [comment]
Looks like it worked.

**Comment by stuartcampbell** [comment]
I verified it! 😊
