### ISSUE TITLE
docs broken, couldn't connect to db

### ISSUE THREAD

**Issue by cowanml** [NSLS-II/docs#38]
inline ipython dumped traceback cuz it can't connect to the db

https://nsls-ii.github.io/broker/basics.html
  /filestore/index.html
  /examples/show-and-plot-scalar-data.html
  /examples/advanced-live-plot.html

**Comment by danielballan** [comment]
Yep, these files are very out of date. Waiting for time to revisit. Will leave this issue open as a reminder.
