### ISSUE TITLE
Metadatastore documents

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/docs#4]
Did we decide that **every** document type in metadatastore has a `time` field?

**Comment by tacaswell** [comment]
I thought everything _but_ `event_descriptors`.

**Comment by danielballan** [comment]
We should decide this at the meeting tomorrow.

My take: every mongo document has a mongo time that one can access if one really needs to. It's not clear that an explicit `time` field would have scientific significance for `event_descriptors` or for that matter `sample` and other snowflake collections.
