### ISSUE TITLE
/DATA, /POOL, broker dns aliases

### ISSUE THREAD

**Issue by cowanml** [NSLS-II/docs#44]
Was doing some fs work on 5id and had this doc pointed out to me.
https://github.com/NSLS-II/docs/blob/master/deploying/metadatastore.rst
- There is not yet a consistent standard (we're working on it) for filesystem naming :(  /DATA and /POOL are not ubiquitous.
- We don't have any write-once filesystems; there's no need for data and analysis to be on different filesystems.
- The "broker" dns alias just adds complexity.  It's much easier to edit/manage/debug the conf files for mds and fs than to make dns changes

**Comment by danielballan** [comment]
FYI That document is old and, although it's extant in the repository, it's not actually linked in the [published documentation](http://nsls-ii.github.io/deployment-details.html) generated from that repo AFAIK.

**Comment by stuartcampbell** [comment]
I've added a comment to the top of the file that some of the information might be out of date.  As this file isn't linked to from anywhere I don't see it will cause much harm.
