### ISSUE TITLE
Sandbox Security Certificate expired

### ISSUE THREAD

**Issue by prjemian** [NSLS-II/docs#71]
The security certificate has expired for the Sandbox.  See attached screen:

![clipboard01](https://user-images.githubusercontent.com/2279984/32126211-18cc4cae-bb35-11e7-9792-ad07d6faa679.png)

times are my local (CDT), I believe.

**Comment by tacaswell** [comment]
This will almost certainly have to go through ITD, probably can not get it fixed until Monday.

**Comment by danielballan** [comment]
Somehow I missed this! Sorry @prjemian. This happened right around the bluesky 1.0 push and I dropped the ball. I fixed it on November 2. I hope the downtime wasn't a major inconvenience for you -- we'll try not to let that happen again.
