### ISSUE TITLE
should add 4 package level hierarchy to docs

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/docs#74]
4 levels of device definition / instantiation

   1. opyhd :: cross facility package, class definition only
   2. nslsii_tools :: nsls-ii specific classes and plans.  Factory
                      functions to make standard objects (ring
                      current, etc)
   3. BEAMLINETOOLS :: beamline specific classes, plans, factory
        functions, maybe direct instatiation of devices
   4. beamline plofile :: maybe class definition (should move up),
        device connection / instatiation

I suggest a new section: NSLS-II packaging practices (or hierarchy)
@tacaswell ?

**Comment by danielballan** [comment]
Ah, just catching up here. I started writing something after the meeting.
