### ISSUE TITLE
suggest IP for host?

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/docs#76]
One issue. For adding a jupyter kernel, I had to change from using the hostname string to a specific IP address. I'm not sure where along the chain the issue is.

However, this could be an issue that others encounter. I'd suggest adding to these docs
https://nsls-ii.github.io/conda.html#access-custom-user-environments-in-nsls-ii-s-jupyterhub

something like:
tip : if you are having kernel connection problems, try replacing the hostname with an actual ip address. You may find your ip address by typing `ip addr` on the host machine.

@danielballan do you agree? i will PR if yes. This issue is also meant to flag this general problem

**Comment by danielballan** [comment]
I'm on the fence about whether to document this workaround. This seems like it that should definitely be fixed at the IT level. Encoding IPs could make our system brittle, so I guess I lean against documenting this. Which machine did you have this problem on?

**Comment by jrmlhermitte** [comment]
just investigated this is my fault. i  used the wrong hostname. too much running and not enough sleeping. closing. Sorry about this!

**Comment by danielballan** [comment]
No worries :- )
